CREATE SEQUENCE actors_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE bookings_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE cities_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE comments_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE countries_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE directors_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE genres_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE halls_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE locations_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE movies_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE seat_rows_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE sessions_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE users_seq START WITH 1 INCREMENT BY 1;